name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t yourdockerhub/hello-world-app .

    - name: Log in to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push Docker image
      run: docker push yourdockerhub/hello-world-app

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.BASTION_IP }}
        username: ec2-user
        key: ${{ secrets.BASTION_SSH_KEY }}
        script: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.APP_PRIVATE_IP }} \
          "docker pull yourdockerhub/hello-world-app && docker run -d -p 80:3000 yourdockerhub/hello-world-app"
